sonar.projectKey=dashboard-app
sonar.projectName=dashboard-app
sonar.sources=server.js,public
sonar.tests=test
sonar.test.inclusions=test/**/*.js
sonar.exclusions=public/jquery-ui-datepicker/**,public/webfonts/**,public/js/*.min.js