sonar.organization=markfosu
sonar.projectKey=markfosu_Administration-Dashboard
sonar.projectName=Administration-Dashboard

sonar.sources=server.js
sonar.tests=test
sonar.test.inclusions=test/**/*.js

sonar.exclusions=public/**